from elixir import *

class GLIAEN(Entity):
  """Internal Account entry"""  
  GLIECONO  = Field(String(3), label='Company ID', primary_key=True)
  GLIENOID  = Field(String(3), label='Numbering ID', primary_key=True)
  GLIEIEID  = Field(Integer, label='Entry ID', primary_key=True)
  GLIESQID  = Field(Integer, label='Sequence ID', primary_key=True)
  GLIETRDT  = Field(Numeric(8,0), label='Transaction date')
  GLIEFSYR  = Field(Integer, label='Fiscal year', index=True)
  GLIEFSPR  = Field(Integer, label='Fiscal date', index=True)
  GLIEACID  = Field(String(48), label='Acct. ID')
  GLIEACFM  = Field(String(48), label='Acct. ID')
  GLIEACNM  = Field(String(32), label='Acct. Name')
  GLIESRLG  = Field(String(2), label='Source ledger')
  GLIESRTP  = Field(String(2), label='Source type')
  GLIETRAM  = Field(Numeric(18,4), label='Amount')
  GLIETRDB  = Field(Numeric(18,4), label='Db. Amount')
  GLIETRCR  = Field(Numeric(18,4), label='Cr. Amount')
  GLIETRTP  = Field(Integer, label='Trans. type')
  GLIECUDC  = Field(Integer, label='Decimal placement')
  GLIECUDC  = Field(Integer, label='Decimal placement')
  GLIECHCD  = Field(String(3), label='Curr')
  GLIECRTP  = Field(String(3), label='Rate type')
  GLIEDTMT  = Field(String(1), label='Date match')
  GLIERTOP  = Field(String(1), label='Rate operation')
  GLIERTDT  = Field(Numeric(8,0), label='Date date')
  GLIERCVL  = Field(Numeric(15,4), label='Def. rate')
  GLIERTVL  = Field(Numeric(15,4), label='Rate value')
  GLIERTSP  = Field(Numeric(15,4), label='Rate spread')
  GLIECSCD  = Field(String(3), label='Func. Curr.')
  GLIECUAM  = Field(Numeric(18,4), label='Func. Amount')
  GLIECUDB  = Field(Numeric(18,4), label='FDb. Amount')
  GLIECUCR  = Field(Numeric(18,4), label='FCr. Amount')
  GLIEIEST  = Field(Integer, label='Status', index=True)
  GLIEISID  = Field(String(2), label='Int. source ID')
  GLIEISDT  = Field(String(2), label='Int. number dt')
  GLIEISNO  = Field(String(12), label='Int. number')
  GLIEAUDT  = Field(Numeric(8, 0), label='Audit date')
  GLIEAUTM  = Field(Numeric(6, 0), label='Audit time')
  GLIEAUUS  = Field(String(24), label='Audit user')  



